export const ADD_NEW_TODO = "ADD_NEW_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const TOGGLE_TODO_STATUS = "TOGGLE_TODO_STATUS";
export const REMOVE_COMPLEATED_TODO = "REMOVE_COMPLEATED_TODO";
